#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

DB_CONFIG_FILE="/portus/config/database.yml"

# Adapter:
DB_ADAPTER="${DB_ADAPTER:-'mysql2'}" && \
sed -i "s#XXX-DB_ADAPTER-XXX#${DB_ADAPTER}#" ${DB_CONFIG_FILE}

# Encoding:
DB_ENCODING="${DB_ENCODING:-'utf8'}" && \
sed -i "s#XXX-DB_ENCODING-XXX#${DB_ENCODING}#" ${DB_CONFIG_FILE}

# Host:
DB_HOST="${DB_HOST:-'db'}" && \
sed -i "s#XXX-DB_HOST-XXX#${DB_HOST}#" ${DB_CONFIG_FILE}

# Port:
DB_PORT="${DB_PORT:-'db'}" && \
sed -i "s#XXX-DB_PORT-XXX#${DB_PORT}#" ${DB_CONFIG_FILE}

# Username:
DB_USERNAME="${DB_USERNAME:-'root'}" && \
sed -i "s#XXX-DB_USERNAME-XXX#${DB_USERNAME}#" ${DB_CONFIG_FILE}

# Password:
DB_PASSWORD="${DB_PASSWORD:-'portus'}" && \
sed -i "s#XXX-DB_PASSWORD-XXX#${DB_PASSWORD}#" ${DB_CONFIG_FILE}

# Database:
DB_DATABASE="${DB_DATABASE:-'portus'}" && \
sed -i "s#XXX-DB_DATABASE-XXX#${DB_DATABASE}#" ${DB_CONFIG_FILE}

# Portus port:
[ "${PORT0}" ] && [ ! "${PORTUS_PORT}" ] && PORTUS_PORT=${PORT0}

#------------------------------------------------------------------------------
# Populate the database:
#------------------------------------------------------------------------------

function mysql_alive() {
  local RETRIES=30; while [ ${RETRIES} -gt 0 ]; do
    timeout -t 2 bash -c "echo > /dev/tcp/${DB_HOST}/${DB_PORT}" &> /dev/null && return 0
    sleep 1; RETRIES=$((RETRIES - 1)); echo -n '.'
  done; echo; return 1
}

echo -n 'Waiting for the database '
mysql_alive || { echo; echo "Ops! Where is ${DB_HOST}:${DB_PORT} ?"; exit 1; }
mysql -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} ${DB_DATABASE} \
-e "show tables" | grep -q 'registries' || bundle exec rake db:setup

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

exec puma -b tcp://0.0.0.0:${PORTUS_PORT:-80} -w 3
