#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

CONFIG_FILE='/portus/config/config.yml'
DB_CONFIG_FILE='/portus/config/database.yml'
SECRETS_CONFIG_FILE='/portus/config/secrets.yml'

# Machine fqdn:
: ${PORTUS_MACHINE_FQDN:=127.0.0.1} && \
sed -i "s#XXX-PORTUS_MACHINE_FQDN-XXX#${PORTUS_MACHINE_FQDN}#" ${CONFIG_FILE}

# Delete enabled:
: ${PORTUS_DELETE_ENABLED:=false} && \
sed -i "s#XXX-PORTUS_DELETE_ENABLED-XXX#${PORTUS_DELETE_ENABLED}#" ${CONFIG_FILE}

# SSL enabled:
: ${PORTUS_CHECK_SSL_USAGE_ENABLED:=true} && \
sed -i "s#XXX-PORTUS_CHECK_SSL_USAGE_ENABLED-XXX#${PORTUS_CHECK_SSL_USAGE_ENABLED}#" ${CONFIG_FILE}

# Adapter:
: ${MARIADB_ADAPTER:=mysql2} && \
sed -i "s#XXX-MARIADB_ADAPTER-XXX#${MARIADB_ADAPTER}#" ${DB_CONFIG_FILE}

# Encoding:
: ${MARIADB_ENCODING:=utf8} && \
sed -i "s#XXX-MARIADB_ENCODING-XXX#${MARIADB_ENCODING}#" ${DB_CONFIG_FILE}

# Host:
: ${MARIADB_HOST:=db} && \
sed -i "s#XXX-MARIADB_HOST-XXX#${MARIADB_HOST}#" ${DB_CONFIG_FILE}

# Port:
: ${MARIADB_PORT:=3306} && \
sed -i "s#XXX-MARIADB_PORT-XXX#${MARIADB_PORT}#" ${DB_CONFIG_FILE}

# Username:
: ${MARIADB_USER:=root} && \
sed -i "s#XXX-MARIADB_USER-XXX#${MARIADB_USER}#" ${DB_CONFIG_FILE}

# Password:
: ${MARIADB_PASSWORD:=portus} && \
sed -i "s#XXX-MARIADB_PASSWORD-XXX#${MARIADB_PASSWORD}#" ${DB_CONFIG_FILE}

# Database:
: ${MARIADB_DATABASE:=portus} && \
sed -i "s#XXX-MARIADB_DATABASE-XXX#${MARIADB_DATABASE}#" ${DB_CONFIG_FILE}

# Secret key base:
: ${PORTUS_SECRET_KEY_BASE:=secret-goes-here} && \
sed -i "s#XXX-PORTUS_SECRET_KEY_BASE-XXX#${PORTUS_SECRET_KEY_BASE}#" ${SECRETS_CONFIG_FILE}

# Encryption private key path:
: ${PORTUS_ENCRYPTION_PRIVATE_KEY_PATH:=/certs/server-key.pem} && \
sed -i "s#XXX-PORTUS_ENCRYPTION_PRIVATE_KEY_PATH-XXX#${PORTUS_ENCRYPTION_PRIVATE_KEY_PATH}#" ${SECRETS_CONFIG_FILE}

# Portus password:
: ${PORTUS_PORTUS_PASSWORD:=portus} && \
sed -i "s#XXX-PORTUS_PORTUS_PASSWORD-XXX#${PORTUS_PORTUS_PASSWORD}#" ${SECRETS_CONFIG_FILE}

# Set Rack and Rails environment:
export RACK_ENV=${RACK_ENV:-production}
export RAILS_ENV=${RAILS_ENV:-production}

#------------------------------------------------------------------------------
# Populate the database:
#------------------------------------------------------------------------------

function mysql_alive() {
  local RETRIES=30; while [ ${RETRIES} -gt 0 ]; do
    timeout -t 2 bash -c "echo > /dev/tcp/${MARIADB_HOST}/${MARIADB_PORT}" &> /dev/null && return 0
    sleep 1; RETRIES=$((RETRIES - 1)); echo -n '.'
  done; echo; return 1
}

echo -n 'Waiting for the database '
mysql_alive || { echo; echo "Ops! Where is ${MARIADB_HOST}:${MARIADB_PORT} ?"; exit 1; }
mysql -h ${MARIADB_HOST} -P ${MARIADB_PORT} -u ${MARIADB_USER} -p${MARIADB_PASSWORD} ${MARIADB_DATABASE} \
-e "show tables" | grep -q 'registries' || {
  env bundle exec rake db:migrate:reset
  env bundle exec rake db:seed
}

#------------------------------------------------------------------------------
# Debug:
#------------------------------------------------------------------------------

[[ "${DEBUG}" == "true" ]] && {
  echo "### ${CONFIG_FILE}"; cat ${CONFIG_FILE}
  echo "### ${DB_CONFIG_FILE}"; cat ${DB_CONFIG_FILE}
  echo "### ${SECRETS_CONFIG_FILE}"; cat ${SECRETS_CONFIG_FILE}
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

[ "${PORT0}" ] && [ ! "${PUMA_PORT}" ] && PUMA_PORT="${PORT0}"
export SSL_CERT_DIR=${SSL_CERT_DIR:-/certs:/usr/local/share/ca-certificates:/etc/ssl/certs} && c_rehash

[[ "${PORTUS_CHECK_SSL_USAGE_ENABLED}" == "true" && "${PUMA_SSL_KEY}" && "${PUMA_SSL_CRT}" ]] && \
exec env puma -e ${RACK_ENV} -b "ssl://${PUMA_IP:-0.0.0.0}:${PUMA_PORT:-443}?key=${PUMA_SSL_KEY}&cert=${PUMA_SSL_CRT}" -w ${PUMA_WORKERS:-3} ||
exec env puma -e ${RACK_ENV} -b "tcp://${PUMA_IP:-0.0.0.0}:${PUMA_PORT:-80}" -w ${PUMA_WORKERS:-3}
