#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

CONFIG_FILE='/portus/config/config.yml'
DB_CONFIG_FILE='/portus/config/database.yml'
SECRETS_CONFIG_FILE='/portus/config/secrets.yml'

# Machine fqdn:
: ${MACHINE_FQDN:-127.0.0.1} && \
sed -i "s#XXX-MACHINE_FQDN-XXX#${MACHINE_FQDN}#" ${CONFIG_FILE}

# Adapter:
: ${DB_ADAPTER:-mysql2} && \
sed -i "s#XXX-DB_ADAPTER-XXX#${DB_ADAPTER}#" ${DB_CONFIG_FILE}

# Encoding:
: ${DB_ENCODING:-utf8} && \
sed -i "s#XXX-DB_ENCODING-XXX#${DB_ENCODING}#" ${DB_CONFIG_FILE}

# Host:
: ${DB_HOST:-db} && \
sed -i "s#XXX-DB_HOST-XXX#${DB_HOST}#" ${DB_CONFIG_FILE}

# Port:
: ${DB_PORT:-3306} && \
sed -i "s#XXX-DB_PORT-XXX#${DB_PORT}#" ${DB_CONFIG_FILE}

# Username:
: ${DB_USERNAME:-root} && \
sed -i "s#XXX-DB_USERNAME-XXX#${DB_USERNAME}#" ${DB_CONFIG_FILE}

# Password:
: ${DB_PASSWORD:-portus} && \
sed -i "s#XXX-DB_PASSWORD-XXX#${DB_PASSWORD}#" ${DB_CONFIG_FILE}

# Database:
: ${DB_DATABASE:-portus} && \
sed -i "s#XXX-DB_DATABASE-XXX#${DB_DATABASE}#" ${DB_CONFIG_FILE}

# Secret key base:
: ${SECRETS_SECRET_KEY_BASE:-secret-goes-here} && \
sed -i "s#XXX-SECRETS_SECRET_KEY_BASE-XXX#${SECRETS_SECRET_KEY_BASE}#" ${SECRETS_CONFIG_FILE}

# Encryption private key path:
: ${SECRETS_ENCRYPTION_PRIVATE_KEY_PATH:-/certs/server-key.pem} && \
sed -i "s#XXX-SECRETS_ENCRYPTION_PRIVATE_KEY_PATH-XXX#${SECRETS_ENCRYPTION_PRIVATE_KEY_PATH}#" ${SECRETS_CONFIG_FILE}

# Portus password:
: ${SECRETS_PORTUS_PASSWORD:-portus} && \
sed -i "s#XXX-SECRETS_PORTUS_PASSWORD-XXX#${SECRETS_PORTUS_PASSWORD}#" ${SECRETS_CONFIG_FILE}

#------------------------------------------------------------------------------
# Populate the database:
#------------------------------------------------------------------------------

function mysql_alive() {
  local RETRIES=30; while [ ${RETRIES} -gt 0 ]; do
    timeout -t 2 bash -c "echo > /dev/tcp/${DB_HOST}/${DB_PORT}" &> /dev/null && return 0
    sleep 1; RETRIES=$((RETRIES - 1)); echo -n '.'
  done; echo; return 1
}

echo -n 'Waiting for the database '
mysql_alive || { echo; echo "Ops! Where is ${DB_HOST}:${DB_PORT} ?"; exit 1; }
mysql -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} ${DB_DATABASE} \
-e "show tables" | grep -q 'registries' || bundle exec rake db:setup

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

[ "${PORT0}" ] && [ ! "${PORTUS_PORT}" ] && PORTUS_PORT="${PORT0}"
export SSL_CERT_DIR=${SSL_CERT_DIR:-/certs} && c_rehash ${SSL_CERT_DIR}
exec env puma -b tcp://0.0.0.0:${PORTUS_PORT:-80} -w 3
